stages:
  - build-option
  - build

job-build-counters:
  stage: build-option
  script:
    - apk add make gcc musl-dev linux-headers
    - ./configure.sh -u counters
    - make

job-build-prometeus:
  stage: build-option
  script:
    - apk add make gcc musl-dev libmicrohttpd-dev
    - ./configure.sh -u load
    - make mojitos_prometeus

job-build-load:
  stage: build-option
  script:
    - apk add make gcc musl-dev
    - ./configure.sh -u load
    - make
    - ./bin/mojitos -a -t 1

job-build-disk:
  stage: build-option
  script:
    - apk add make gcc musl-dev
    - ./configure.sh -u disk
    - make

job-build-network:
  stage: build-option
  script:
    - apk add make gcc musl-dev
    - ./configure.sh -u network
    - make

job-build-rapl:
  stage: build-option
  script:
    - apk add make gcc musl-dev
    - ./configure.sh -u rapl
    - make

job-build:
  stage: build
  script:
    - apk add make gcc musl-dev linux-headers
    - ./configure.sh
    - make

job-build-prometeus:
  stage: build
  script:
    - apk add make gcc musl-dev linux-headers libmicrohttpd-dev
    - ./configure.sh
    - make mojitos_prometeus

job-build-clang:
  stage: build
  script:
    - apk add make clang musl-dev linux-headers
    - ./configure.sh
    - sed -i "s/CC = gcc/CC = clang/" makefile
    - make

job-build-test:
  stage: build
  script: 
    - apk add make gcc musl-dev linux-headers
    - ./configure.sh
    - make tests

workflow:
  name: 'Pipeline for branch: $CI_COMMIT_BRANCH'
