stages:
  - build-option
  - build

job-build-counters:
  stage: build-option
  script:
    - apk add make gcc musl-dev linux-headers
    - ./configure -u counters
    - make

job-build-prometheus:
  stage: build-option
  script:
    - apk add make gcc musl-dev libmicrohttpd-dev
    - ./configure -u load
    - make mojitos_prometheus

job-build-load:
  stage: build-option
  script:
    - apk add make gcc musl-dev
    - ./configure -u load
    - make
    - ./bin/mojitos -u -f 4 -t 1

job-build-disk:
  stage: build-option
  script:
    - apk add make gcc musl-dev
    - ./configure -u disk
    - make
    - ./bin/mojitos -a -f 4 -t 1

job-build-network:
  stage: build-option
  script:
    - apk add make gcc musl-dev
    - ./configure -u network
    - make
    - ./bin/mojitos -d X -f 4 -t 1

job-build-rapl:
  stage: build-option
  script:
    - apk add make gcc musl-dev
    - ./configure -u rapl
    - make

job-build:
  stage: build
  script:
    - apk add make gcc musl-dev linux-headers
    - ./configure
    - make

job-build-prometheus:
  stage: build
  script:
    - apk add make gcc musl-dev linux-headers libmicrohttpd-dev
    - ./configure
    - make mojitos_prometheus

job-build-clang:
  stage: build
  script:
    - apk add make clang musl-dev linux-headers
    - ./configure
    - sed -i "s/CC = gcc/CC = clang/" makefile
    - make

job-build-cpp:
  stage: build
  script:
    - apk add make g++ musl-dev linux-headers
    - ./configure
    - sed -i "s/CC = gcc/CC = c++/" makefile
    - sed -i "s/gnu99/c++20 -Wno-error=write-strings/" makefile
    - make

job-build-test:
  stage: build
  script: 
    - apk add make gcc musl-dev linux-headers
    - ./configure
    - make tests

workflow:
  name: 'Pipeline for branch: $CI_COMMIT_BRANCH'
