.Dd January 9, 2023
.Dt MOJITOS 1
.Os
.Sh NAME
.Nm mojitos
.Nd An open source system, energy and network monitoring tool.
.Sh SYNOPSIS
.Nm mojitos
.Op Fl rsu
.Op Fl t Ar time
.Op Fl f Ar freq
.Op Fl p Ar perf_list
.Op Fl d Ar net_device
.Op Fl o Ar logfile
.Op Fl e Ar cmd ...
.Nm mojitos
.Op Fl l
.Sh DESCRIPTION
.Nm
enables to monitor the system, its energy comsumption and the network activity, at the OS level.
It runs on GNU/Linux.
.Pp
.Nm
supports the following options:
.Bl -tag -width Ds
.It Fl s
Enable overhead statistics (in nanoseconds).
.It Fl u
Enable system-level load monitoring.
.It Fl r
Enable RAPL.
.It Fl p Ar perf_list
Enable performance counters.
The argument is a coma separated list of performance counters.
.It Fl d Ar net_device
Enable network monitoring.
.It Fl l
List the available performance counters and quit.
.It Fl t Ar time
Set duration value (in seconds). If 0, then loops indefinitely.
.It Fl f Ar freq
Set amount of measurements per second.
.It Fl e Ar cmd ...
Execute a command with optional arguments.
If this option is used, any usage of -t or -f is ignored.
.El
.Sh EXIT STATUS
.Ex
.Sh EXAMPLES
RAPL values during 2 seconds with a frequency of 2Hz:
.Bd -literal -offset indent
$ mojitos -t 2 -f 2 -r
#timestamp package-00 core0 dram0
1036389.135659868 10986 2869 1526
1036389.500183551 1291440 255736 515562
1036390.000754048 1333553 228393 689513
1036390.500113978 1581967 267944 701536
.Ed
.Pp
Performance counters (cpu_cycle, cache_ll_r_a and page_faults) during 4 seconds
with a frequency of 1Hz.
In the context of cache performance counters (as with "cache_ll_r_a"),
 _r and _w suffixes mean respectively read and write,
while the _a, _m and _p ones mean respectively access, miss and pending.
.Pp
.Bd -literal -offset indent
$ ./mojitos -t 4 -f 1 -p cpu_cycles,cache_ll_r_a,page_faults
#timestamp cpu_cycles cache_ll page_faults
1036846.351749455 571199 1232 0
1036847.001098880 348173344 2451387 872
1036848.000166158 388112961 2509305 791
1036849.000191883 402255979 2625283 799
.Ed
.Pp
Network values with no time limit with a frequency of 1Hz.
rxp and txp are the number of received and sent packets, while rxb and txp are
the number of received and sent bytes.
.Pp
.Bd -literal -offset indent
$ ./mojitos -t 0 -f 1 -d enp0s25
#timestamp rxp rxb txp txb
1036559.277376027 0 0 0 0
1036560.000161101 4 581 2 179
1036561.000083968 178 268675 55 4954
1036562.000076162 11 1010 5 510
1036563.000069724 17 1643 12 3602
1036564.000113394 990 1493008 369 27299
.Ed
.Pp
overhead of the monitoring when using RAPL and the cpu_cycle performance counter:
.Pp
.Bd -literal -offset indent
$ ./mojitos -t 5 -f 1 -p cpu_cycles -r -s
#timestamp cpu_cycles package-00 core0 dram0 overhead
1036988.197227391 162214 19898 4944 1586 149612
1036989.000151326 332613664 2513116 379577 1115171 739573
1036990.000116433 482150700 3321341 587218 1380673 315719
1036991.000182835 525984292 3592582 691221 1385982 272182
1036992.000165117 397678789 2770561 444030 1375729 510379
.Ed
.Sh SEE ALSO
.Xr perf 1 ,
.Xr lscpu 1 ,
.Xr sysfs 5 ,
.Xr proc 5
.Sh BUGS
Yes.
